import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav>
            <ul>
              <li>LOGO</li>
              <li>
                <Link href={""}>Accueil</Link>
              </li>
              <li>
                <Link href={""}>Profil</Link>
              </li>
              <li>
                <Link href={""}>Réglages</Link>
              </li>
              <li>
                <Link href={""}>Communauté</Link>
              </li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
